### ISSUE TITLE
Get rid of compiler-builtins (and cargo) fork

### ISSUE THREAD

**Issue by mrk-its** [mrk-its/rust-mos#21]
We are forking compiler builtins to apply such little patch: https://github.com/mrk-its/compiler-builtins/commit/384dcad08d0e920229167eac82553046d0e1188b
Cargo is forked because we need force usage of compiler-builtins fork - getting rid of it would greatly simplify releasing.

Let's investigate why compilation of these `int` and `float` modules fail

**Comment by mlund** [comment]
This is the error coming from vanilla compiler-builtins:
``` console
LLVM ERROR: unable to legalize instruction: %37:_(s32) = G_FDIV %36:_, %31:_ (in function: _ZN17compiler_builtins5float3pow9__powisf217h041f3b35704658baE)
error: could not compile `compiler_builtins` (lib)
```
`powisf2` appears [here](https://github.com/search?q=repo%3Amrk-its%2Fcompiler-builtins+powisf2&type=code).
The error seems simply to be due to a missing `pow()` function on the C side of things (the SDK still doesn't support floats, see https://github.com/llvm-mos/llvm-mos-sdk/issues/58)

**Comment by mlund** [comment]
Could [this patch](https://github.com/mrk-its/cargo/blob/bc51af01cda30bfd45f73bf3631e0ad18be05b85/src/cargo/core/compiler/standard_lib.rs#L91) be achieved from `Cargo.toml`?, i.e. something like the following:

``` toml
[dependencies]
compiler-builtins = { git = "https://github.com/mrk-its/compiler-builtins.git }
```

**Comment by mrk-its** [comment]
> Could [this patch](https://github.com/mrk-its/cargo/blob/bc51af01cda30bfd45f73bf3631e0ad18be05b85/src/cargo/core/compiler/standard_lib.rs#L91) be achieved from Cargo.toml?, i.e. something like the following:

no, patching this way unfortunately doesn't work (at least it didn't last time I was checking, maybe something changed in the meantime)

**Comment by mlund** [comment]
Perhaps we could figure out how this is handled for other targets without floating point support. There are mentions of "soft-float".

**Comment by mrk-its** [comment]
llvm-mos got floats support recently: https://github.com/llvm-mos/llvm-mos/issues/10 
And it looks compiler-builtins patching is no longer necessary.
