### ISSUE TITLE
create docker image for rust-mos

### ISSUE THREAD

**Issue by ghost** [mrk-its/rust-mos#3]
It maybe a benefit for a lot of people if there were a docker file that would generate a working rust-mos container so that most users don't have to compile it themselves on their own systems.

**Comment by ghost** [comment]
> It maybe a benefit for a lot of people if there were a docker file that would generate a working rust-mos container so that most users don't have to compile it themselves on their own systems.

I am gonna try to put a docker file together that accomplishes this.  I hope to create something so that a user can just type a couple commands to create the container, run rust from the container to generate the Mos executable.

**Comment by mrk-its** [comment]
I'm already preparing docker images, mainly for vscode devcontainer, but they can be used also standalone probably: https://hub.docker.com/repository/docker/mrkits/rust-mos

You can find dockerfiles here: https://github.com/mrk-its/rust-mos-docker

**Comment by mrk-its** [comment]
And here is example project including vscode devcontainer configuration: https://github.com/mrk-its/rust-mos-hello-world

**Comment by ghost** [comment]
Awesome..  I will take a look
