### ISSUE TITLE
Arrays larger than 32 kB not possible

### ISSUE THREAD

**Issue by mlund** [mrk-its/rust-mos#6]
The following gives a compiler error:
~~~ rust
pub const DEFAULT_BASIC_AREA : *mut [u8; 38911] = (0x0801) as *mut [u8; 38911];
~~~
with the following message:
~~~
error[E0080]: values of the type `[u8; 38911]` are too big for the current architecture
  --> src/c64.rs:79:1
   |
79 | pub const DEFAULT_BASIC_AREA : *mut [u8; 38911] = (0x0801) as *mut [u8; 38911];
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: The rules on what exactly is undefined behavior aren't clear, so this check might be overzealous. Please open an issue on the rustc repository if you believe it should not be considered undefined behavior.
   = note: the raw bytes of the constant (size: 2, align: 1) {
               01 08                                           │ ..
           }
~~~

I'm not sure where this limitation comes from as the memory region is within the 16-bit address space of the 6502.

**Comment by mlund** [comment]
As [discussed here](https://stackoverflow.com/questions/58732657/how-many-elements-can-a-rust-array-have), the reason is that the maximum array length is defined by `isize::MAX == 32767`. I think `usize::MAX`, i.e.  64 kB would have been more reasonable as the 8-bit systems are already quite limited. But perhaps difficult to change due to signed pointer arithmetics:

- https://stackoverflow.com/questions/58732657/how-many-elements-can-a-rust-array-have
- https://github.com/rust-lang/rust/issues/18726

**Comment by mlund** [comment]
I'm not sure there's any solution to this(?), so fine to close.

**Comment by mrk-its** [comment]
Let's close it, it looks it is more upstream rust issue.
